name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      
    - name: Install dependencies
      run: |
        rustup update
        cargo build --verbose
        
    - name: Test
      run: cargo test
      
    - name: Test with Code Coverage
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --out Html --output-dir ./coverage
