name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable
    - name: Install dependencies
      run: |
        rustup update
        cargo build --verbose
    - name: Test
      run: cargo test
